name: Create Release
on:
  workflow_dispatch:

jobs:
  check:
    name: Check Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Packages
        run: sudo apt-get install -y curl jq grep
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Get release tags
        run: |
          echo "url = $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/releases"
          releases=$(curl -s https://api.github.com/repos/enolgor/gateway/releases | jq -r '.[].tag_name')
          release_not_exists=$(echo "$releases" | grep -q "0.6.2"; echo $?;)
          echo $release_not_exists
          let ret=1-$release_not_exists
          echo $ret
          exit ret
  deploy:
    needs: check
    if: needs.check.outputs.status == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Test output
        run: echo "job run"
