name: Create Release
on:
  workflow_dispatch:

jobs:
  check:
    name: Check Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Packages
        run: sudo apt-get install -y curl jq grep
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Get current version
        id: getversion
        run: |
          version=$(mvn -f src/pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo ::set-output version=$version
      - name: Check current version against released tags
        run: |
          echo "url = $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/releases"
          releases=$(curl -s https://api.github.com/repos/enolgor/gateway/releases | jq -r '.[].tag_name')
          release_not_exists=$(echo "$releases" | grep -q "${{ steps.getversion.outputs.version }}"; echo $?;)
          if [ "$release_not_exists" -eq "1" ]; then exit 0; else exit 1; fi
      - name: Deploy artifacts
        run: mvn clean deploy
