name: Create Release
on:
  workflow_dispatch:

jobs:
  check:
    name: Check Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Packages
        run: sudo apt-get install -y curl jq
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Get release tags
        run: |
          echo "url = $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/releases"
          release_exists=$(curl -s https://api.github.com/repos/enolgor/gateway/releases | jq -r '.[].tag_name' | grep -c "0.6.0")
          exit $release_exists          
  deploy:
    needs: check
    if: needs.check.outputs.status == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Test output
        run: echo "job run"
