name: Test
on:
  workflow_dispatch:

jobs:
  release:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Settingsxml
        run: |
          cat <<EOT >> settings.xml
          <?xml version="1.0" encoding="UTF-8"?>
          <settings xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd" xmlns="http://maven.apache.org/SETTINGS/1.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
          <servers>
            <server>
              <username>admin</username>
              <password>AP374jQEzVTsHJfcyutWW11wucc</password>
              <id>central</id>
            </server>
            <server>
              <username>admin</username>
              <password>AP374jQEzVTsHJfcyutWW11wucc</password>
              <id>snapshots</id>
            </server>
           </servers>
          </settings>
          EOT
          cat settings.xml

