name: Test
on:
  workflow_dispatch:

jobs:
  release:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: test
        run: |
          cd $HOME && echo $(pwd)
          cd $HOME && ls -al
      - name: Settingsxml
        run: |
          cat <<EOT >> settings.xml
          <?xml version="1.0" encoding="UTF-8"?>
          <settings xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd" xmlns="http://maven.apache.org/SETTINGS/1.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
          <servers>
            <server>
              <username>${{ secrets.MAVEN_USER }}</username>
              <password>${{ secrets.MAVEN_PWD }}</password>
              <id>central</id>
            </server>
            <server>
              <username>${{ secrets.MAVEN_USER }}</username>
              <password>${{ secrets.MAVEN_PWD }}</password>
              <id>snapshots</id>
            </server>
           </servers>
          </settings>
          EOT
          cat settings.xml

